# -*- coding: utf-8 -*-
"""stremlitテスト

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CyNbdkB8rLu95baSpW3P2JHQ1YrTZVgK
"""

!pip install streamlit
import streamlit as st

st.title("Hello World Test App")
if st.button("Click me!"):
    st.write("Hello World!")